import { fork } from "node:child_process";
import { fileURLToPath } from "node:url";

export const SHARE_PROCESS_LIMITS = Object.freeze({
  inputBytes: 6 * 1024 * 1024,
  outputBytes: 4 * 1024 * 1024,
  metadataBytes: 64 * 1024,
  timeoutMs: 3_500,
  childHeapMiB: 192,
});

const WORKER_PATH = fileURLToPath(new URL("./socialShareCardWorker.js", import.meta.url));
const PNG_SIGNATURE = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]);

export class SocialShareCardProcessError extends Error {
  constructor(code, cause) {
    super("Social share card processing failed safely.", cause ? { cause } : undefined);
    this.name = "SocialShareCardProcessError";
    this.code = code;
  }
}

function boundedJson(value, maximum) {
  let encoded;
  try { encoded = JSON.stringify(value); }
  catch (cause) { throw new SocialShareCardProcessError("renderer_protocol", cause); }
  if (typeof encoded !== "string" || Buffer.byteLength(encoded, "utf8") > maximum) {
    throw new SocialShareCardProcessError("renderer_resource_limit");
  }
  return encoded;
}

function bufferView(value) {
  return Buffer.isBuffer(value) ? value
    : value instanceof Uint8Array ? Buffer.from(value.buffer, value.byteOffset, value.byteLength) : null;
}

// Shared validation at both ends of IPC; never forward a caller's functions,
// fetch clients, credentials, database objects, or AbortSignal into the child.
export function normalizedShareProcessInput(model, { artworkBytes, artworkDataUri = "", artwork = null } = {}) {
  if (!model || typeof model !== "object" || Array.isArray(model)
    || !["going", "interested", "review"].includes(model.variant)) {
    throw new SocialShareCardProcessError("renderer_protocol");
  }
  const metadata = boundedJson({ model, artwork }, SHARE_PROCESS_LIMITS.metadataBytes);
  const input = artworkBytes == null ? null : bufferView(artworkBytes);
  if (artworkBytes != null && (!input || input.byteLength < 12)) {
    throw new SocialShareCardProcessError("renderer_protocol");
  }
  const dataUri = artworkDataUri == null ? "" : artworkDataUri;
  if (typeof dataUri !== "string") throw new SocialShareCardProcessError("renderer_protocol");
  // The low-level renderer accepts only bounded, prepared JPEG data URIs.
  // Check length before regex validation so an oversized string is never scanned.
  if ((input?.byteLength || 0) > SHARE_PROCESS_LIMITS.inputBytes
    || dataUri.length > 3 * 1024 * 1024
    || (input?.byteLength || 0) + Buffer.byteLength(dataUri, "utf8")
      + Buffer.byteLength(metadata, "utf8") > SHARE_PROCESS_LIMITS.inputBytes + SHARE_PROCESS_LIMITS.metadataBytes) {
    throw new SocialShareCardProcessError("renderer_resource_limit");
  }
  if (dataUri && !/^data:image\/jpeg;base64,[A-Za-z0-9+/]+={0,2}$/u.test(dataUri)) {
    throw new SocialShareCardProcessError("renderer_protocol");
  }
  const decoded = JSON.parse(metadata);
  return { model: decoded.model, artwork: decoded.artwork, artworkBytes: input, artworkDataUri: dataUri };
}

export function normalizedShareProcessResult(result) {
  const bytes = bufferView(result?.bytes);
  if (!bytes || bytes.byteLength < 100 || bytes.byteLength > SHARE_PROCESS_LIMITS.outputBytes
    || !bytes.subarray(0, PNG_SIGNATURE.length).equals(PNG_SIGNATURE)
    || typeof result?.artworkApplied !== "boolean") {
    throw new SocialShareCardProcessError("renderer_protocol");
  }
  const artwork = result.artwork ?? null;
  if (artwork !== null && (typeof artwork !== "object" || Array.isArray(artwork))) {
    throw new SocialShareCardProcessError("renderer_protocol");
  }
  const metadata = boundedJson(artwork, SHARE_PROCESS_LIMITS.metadataBytes);
  return Object.freeze({ bytes, artworkApplied: result.artworkApplied, artwork: JSON.parse(metadata) });
}

function childEnvironment() {
  const env = {
    NODE_ENV: "production",
    UV_THREADPOOL_SIZE: "1",
    // VIPS_BLOCK_UNTRUSTED also disables the trusted SVG generated by our
    // renderer. The worker separately admits only JPEG/PNG/WebP source bytes.
    MALLOC_ARENA_MAX: "2",
  };
  for (const key of [
    "PATH", "SystemRoot", "WINDIR", "TEMP", "TMP", "TMPDIR",
    "LANG", "LC_ALL", "LD_LIBRARY_PATH", "DYLD_LIBRARY_PATH",
  ]) {
    if (typeof process.env[key] === "string") env[key] = process.env[key];
  }
  return env;
}

function abortReason(signal) {
  return signal?.reason instanceof Error ? signal.reason
    : new DOMException("Social share rendering was cancelled.", "AbortError");
}

// Admission belongs to the higher-level renderer. There is deliberately no
// lease or queue here: it must hold its existing lease until this promise settles.
export function createIsolatedSocialShareCardRenderer({
  forkImpl = fork, setTimer = setTimeout, clearTimer = clearTimeout,
} = {}) {
  return async function render(model, { signal, ...options } = {}) {
    if (signal?.aborted) throw abortReason(signal);
    const input = normalizedShareProcessInput(model, options);
    return new Promise((resolve, reject) => {
      let child;
      let timer;
      let outcome = null;
      let closed = false;
      const terminate = () => {
        if (!child?.pid || closed) return;
        try { child.kill("SIGKILL"); }
        catch (error) { if (error?.code !== "ESRCH") void error; }
      };
      const fail = (error) => {
        if (closed) return;
        if (!outcome) outcome = { error };
        terminate();
      };
      const onAbort = () => {
        if (closed) return;
        outcome = { error: abortReason(signal) };
        terminate();
      };
      try {
        child = forkImpl(WORKER_PATH, [], {
          env: childEnvironment(),
          execArgv: [`--max-old-space-size=${SHARE_PROCESS_LIMITS.childHeapMiB}`, "--max-semi-space-size=8"],
          serialization: "advanced",
          stdio: ["ignore", "ignore", "ignore", "ipc"],
          windowsHide: true,
        });
      } catch (cause) {
        reject(new SocialShareCardProcessError("renderer_unavailable", cause));
        return;
      }
      child.once("message", (message) => {
        if (outcome || closed) return;
        try {
          if (message?.ok !== true) throw new SocialShareCardProcessError("renderer_failed");
          outcome = { value: normalizedShareProcessResult(message.result) };
        } catch (error) { outcome = { error }; }
        // Even success waits for process death, reclaiming native Sharp memory
        // before the caller can release admission or begin another render.
        terminate();
      });
      child.once("error", (cause) => fail(new SocialShareCardProcessError("renderer_unavailable", cause)));
      child.once("close", () => {
        if (closed) return;
        closed = true;
        clearTimer(timer);
        signal?.removeEventListener("abort", onAbort);
        if (outcome?.error) reject(outcome.error);
        else if (outcome?.value) resolve(outcome.value);
        else reject(new SocialShareCardProcessError("renderer_unavailable"));
      });
      timer = setTimer(() => fail(new SocialShareCardProcessError("renderer_timeout")), SHARE_PROCESS_LIMITS.timeoutMs);
      timer.unref?.();
      signal?.addEventListener("abort", onAbort, { once: true });
      if (signal?.aborted) { onAbort(); return; }
      try {
        child.send(input, (cause) => {
          if (cause) fail(new SocialShareCardProcessError("renderer_unavailable", cause));
        });
      } catch (cause) { fail(new SocialShareCardProcessError("renderer_unavailable", cause)); }
    });
  };
}

// Creating the function does not start a worker or import the renderer. This
// remains safe when the worker imports the renderer which imports this module.
export const renderIsolatedSocialShareCard = createIsolatedSocialShareCardRenderer();
