import test, { after } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
const dataDir = mkdtempSync(join(tmpdir(), "pit-analytics-visibility-"));
process.env.PIT_DATA_DIR = dataDir;
const {db}=await import("./db.js");
after(() => { db.close(); rmSync(dataDir, { recursive: true, force: true }); });
const {ingestAnalyticsBatch}=await import("./analyticsService.js");
const extras=JSON.stringify({analyticsConsentAt:1});
const insert=db.prepare("INSERT INTO users(id,email,name,handle,pass_hash,extras,created_at) VALUES(?,?,?,?,?,?,1)");
insert.run("analytics_reader","reader@example.test","Reader","analytics_reader","test",extras);
insert.run("analytics_writer","writer@example.test","Writer","analytics_writer","test",extras);
const user={id:"analytics_reader"};
db.prepare("INSERT INTO posts(id,user_id,artist,venue,overall,kind,created_at) VALUES('news_visibility','analytics_writer','Artist','',0,'status',1)").run();
let sequence=0;
const send=()=>ingestAnalyticsBatch({user,requireIds:true,events:[{id:"evt_visibility_"+(++sequence),name:"feed_impression",props:{postId:"news_visibility",position:0,surface:"news",algorithm:"chronological-v1"}}]});
test("news measurement counts only visible posts and active consenting actors",()=>{
  assert.equal(send().stored,1);
  db.prepare("INSERT INTO blocks(blocker_id,blocked_id,created_at) VALUES('analytics_writer','analytics_reader',1)").run();
  assert.equal(send().stored,0);
  db.prepare("DELETE FROM blocks WHERE blocker_id='analytics_writer'").run();
  db.prepare("UPDATE posts SET removed=1 WHERE id='news_visibility'").run();assert.equal(send().stored,0);
  db.prepare("UPDATE posts SET removed=0 WHERE id='news_visibility'").run();
  db.prepare("UPDATE users SET is_banned=1 WHERE id='analytics_writer'").run();assert.equal(send().stored,0);
  db.prepare("UPDATE users SET is_banned=0 WHERE id='analytics_writer'").run();
  db.prepare("UPDATE users SET dormant_at=1 WHERE id='analytics_reader'").run();assert.equal(send().stored,0);
  db.prepare("UPDATE users SET dormant_at=NULL,extras='{}' WHERE id='analytics_reader'").run();assert.equal(send().stored,0);
  const ignored = send();
  assert.equal(ignored.received, 0, "non-consenting callers receive no content-visibility feedback");
});
