// Curated song list for the profile music picker (pick from a list, Spotify-
// style, instead of typing). "Listen" opens a legal search on YouTube; a real
// build swaps in Spotify/Apple 30s previews via their API.
export const SONGS = [
  { id: "s1", title: "HEALING", artist: "Turnstile" },
  { id: "s2", title: "Mystery", artist: "Turnstile" },
  { id: "s3", title: "Be Sweet", artist: "Japanese Breakfast" },
  { id: "s4", title: "Paprika", artist: "Japanese Breakfast" },
  { id: "s5", title: "$20", artist: "boygenius" },
  { id: "s6", title: "Not Strong Enough", artist: "boygenius" },
  { id: "s7", title: "Kyoto", artist: "Phoebe Bridgers" },
  { id: "s8", title: "Motion Sickness", artist: "Phoebe Bridgers" },
  { id: "s9", title: "Cool About It", artist: "boygenius" },
  { id: "s10", title: "3D Country", artist: "Geese" },
  { id: "s11", title: "Cowboy Nudes", artist: "Geese" },
  { id: "s12", title: "Bull Believer", artist: "Wednesday" },
  { id: "s13", title: "Do It Faster", artist: "Militarie Gun" },
  { id: "s14", title: "Colossus", artist: "IDLES" },
  { id: "s15", title: "Danny Nedelko", artist: "IDLES" },
  { id: "s16", title: "Time (You and I)", artist: "Khruangbin" },
  { id: "s17", title: "White Gloves", artist: "Khruangbin" },
  { id: "s18", title: "Rattlesnake", artist: "King Gizzard & the Lizard Wizard" },
  { id: "s19", title: "Space Song", artist: "Beach House" },
  { id: "s20", title: "Myth", artist: "Beach House" },
  { id: "s21", title: "Simulation Swarm", artist: "Big Thief" },
  { id: "s22", title: "Not", artist: "Big Thief" },
  { id: "s23", title: "Pristine", artist: "Snail Mail" },
  { id: "s24", title: "Working for the Knife", artist: "Mitski" },
  { id: "s25", title: "Nobody", artist: "Mitski" },
  { id: "s26", title: "Your Best American Girl", artist: "Mitski" },
  { id: "s27", title: "Bad Decisions", artist: "Sabrina Carpenter" },
  { id: "s28", title: "Espresso", artist: "Sabrina Carpenter" },
  { id: "s29", title: "Good Luck, Babe!", artist: "Chappell Roan" },
  { id: "s30", title: "Pink Pony Club", artist: "Chappell Roan" },
  { id: "s31", title: "vampire", artist: "Olivia Rodrigo" },
  { id: "s32", title: "get him back!", artist: "Olivia Rodrigo" },
  { id: "s33", title: "Stick Season", artist: "Noah Kahan" },
  { id: "s34", title: "Something in the Orange", artist: "Zach Bryan" },
  { id: "s35", title: "Not Like Us", artist: "Kendrick Lamar" },
  { id: "s36", title: "Bad Habit", artist: "Steve Lacy" },
  { id: "s37", title: "Snooze", artist: "SZA" },
  { id: "s38", title: "Kill Bill", artist: "SZA" },
  { id: "s39", title: "Lunch", artist: "Billie Eilish" },
  { id: "s40", title: "BIRDS OF A FEATHER", artist: "Billie Eilish" },
  { id: "s41", title: "Cruel Summer", artist: "Taylor Swift" },
  { id: "s42", title: "Houdini", artist: "Dua Lipa" },
  { id: "s43", title: "Lose Control", artist: "Teddy Swims" },
  { id: "s44", title: "The Less I Know the Better", artist: "Tame Impala" },
  { id: "s45", title: "Borderline", artist: "Tame Impala" },
  { id: "s46", title: "Take Me Out", artist: "Franz Ferdinand" },
  { id: "s47", title: "Do I Wanna Know?", artist: "Arctic Monkeys" },
  { id: "s48", title: "505", artist: "Arctic Monkeys" },
  { id: "s49", title: "Bags", artist: "Clairo" },
  { id: "s50", title: "Chinatown", artist: "Mac DeMarco" },
];

const yt = (s) => `https://www.youtube.com/results?search_query=${encodeURIComponent(`${s.artist} ${s.title}`)}`;
export const listenUrl = yt;
